name: Ruby

on:
  push:
    branches:
      - "**"

  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    strategy:
      matrix:
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"
          - "3.1"
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
